/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Flashcard {
  'id' : bigint,
  'question' : string,
  'answer' : string,
}
export interface FlashcardDeck {
  'id' : bigint,
  'title' : string,
  'progress' : bigint,
  'cardCount' : bigint,
}
export interface QuizQuestion {
  'id' : bigint,
  'question' : string,
  'explanation' : string,
  'correctAnswer' : bigint,
  'options' : Array<string>,
}
export interface QuizResult {
  'score' : bigint,
  'totalQuestions' : bigint,
  'subjectId' : bigint,
}
export interface Subject {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'iconName' : string,
  'quizCount' : bigint,
}
export interface UserProgress {
  'completedQuizzes' : bigint,
  'streakDays' : bigint,
  'dailyActivity' : Array<bigint>,
  'accuracy' : bigint,
}
export interface _SERVICE {
  'getFlashcardDecks' : ActorMethod<[bigint], Array<FlashcardDeck>>,
  'getFlashcards' : ActorMethod<[bigint], Array<Flashcard>>,
  'getQuizQuestions' : ActorMethod<[bigint], Array<QuizQuestion>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getUserProgress' : ActorMethod<[], [] | [UserProgress]>,
  'initialize' : ActorMethod<[], undefined>,
  'startFlashcardAttempt' : ActorMethod<[bigint, bigint], boolean>,
  'submitQuizResult' : ActorMethod<[QuizResult], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];