/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FlashcardDeck = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'progress' : IDL.Nat,
  'cardCount' : IDL.Nat,
});
export const Flashcard = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
  'quizCount' : IDL.Nat,
});
export const UserProgress = IDL.Record({
  'completedQuizzes' : IDL.Nat,
  'streakDays' : IDL.Nat,
  'dailyActivity' : IDL.Vec(IDL.Nat),
  'accuracy' : IDL.Nat,
});
export const QuizResult = IDL.Record({
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'subjectId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getFlashcardDecks' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FlashcardDeck)],
      ['query'],
    ),
  'getFlashcards' : IDL.Func([IDL.Nat], [IDL.Vec(Flashcard)], ['query']),
  'getQuizQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(QuizQuestion)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getUserProgress' : IDL.Func([], [IDL.Opt(UserProgress)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'startFlashcardAttempt' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'submitQuizResult' : IDL.Func([QuizResult], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FlashcardDeck = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'progress' : IDL.Nat,
    'cardCount' : IDL.Nat,
  });
  const Flashcard = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'answer' : IDL.Text,
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
    'quizCount' : IDL.Nat,
  });
  const UserProgress = IDL.Record({
    'completedQuizzes' : IDL.Nat,
    'streakDays' : IDL.Nat,
    'dailyActivity' : IDL.Vec(IDL.Nat),
    'accuracy' : IDL.Nat,
  });
  const QuizResult = IDL.Record({
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'subjectId' : IDL.Nat,
  });
  
  return IDL.Service({
    'getFlashcardDecks' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FlashcardDeck)],
        ['query'],
      ),
    'getFlashcards' : IDL.Func([IDL.Nat], [IDL.Vec(Flashcard)], ['query']),
    'getQuizQuestions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(QuizQuestion)],
        ['query'],
      ),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getUserProgress' : IDL.Func([], [IDL.Opt(UserProgress)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'startFlashcardAttempt' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'submitQuizResult' : IDL.Func([QuizResult], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };